'use strict';

module.exports = {
  FOOD_CREATE: 'FOOD_CREATE',
  FOOD_COMPLETE: 'FOOD_COMPLETE',
  FOOD_DESTROY: 'FOOD_DESTROY',
  FOOD_DESTROY_COMPLETED: 'FOOD_DESTROY_COMPLETED',
  FOOD_TOGGLE_COMPLETE_ALL: 'FOOD_TOGGLE_COMPLETE_ALL',
  FOOD_UNDO_COMPLETE: 'FOOD_UNDO_COMPLETE',
  FOOD_UPDATE_TEXT: 'FOOD_UPDATE_TEXT',
  USER_SIGNIN: 'USER_SIGNIN',
  USER_SIGNOUT: 'USER_SIGNOUT',
  USER_UPDATE: 'USER_UPDATE'
};
